source 'https://rubygems.org'
gem "activerecord"
gem 'activerecord-jdbcmysql-adapter'
gem 'composite_primary_keys', '>8.0.0'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'rake'
gem 'activesupport'
gem 'puma'
gem 'mini_magick'